import type { Exercise, BodyPart } from '@/lib/types';

export const exercises: Exercise[] = [
  {
    id: 'push-up',
    name: 'Push Up',
    bodyPart: 'Chest',
    sets: 3,
    reps: '15-20',
    instructions: [
      'Get down on all fours, placing your hands slightly wider than your shoulders.',
      'Straighten your arms and legs.',
      'Lower your body until your chest nearly touches the floor.',
      'Push yourself back up.',
      'Repeat for the desired number of repetitions.',
    ],
    reelUrls: ['https://www.instagram.com/reel/C2M0X4_xN9j/', 'https://www.instagram.com/reel/C6i3eJdIUXA/'],
    image: 'push-up-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/Push%20up%20best%20exercises%203d%20animation%20video%20idea%20_%20_workout%20_excercise%20_gym%20_fitness%20_reels%20_inst.mp4?updatedAt=1760782082699',
  },
  {
    id: 'bench-press',
    name: 'Bench Press',
    bodyPart: 'Chest',
    sets: 4,
    reps: '8-12',
    instructions: [
      'Lie flat on a bench with your feet firmly on the ground.',
      'Grip the barbell with hands slightly wider than shoulder-width apart.',
      'Unrack the barbell and hold it straight over your chest.',
      'Lower the bar to your mid-chest.',
      'Push the bar back up until your arms are fully extended.',
    ],
    reelUrls: ['https://www.instagram.com/reel/DLEARYSTG0_/?igsh=MTl1eWJqOHBzb2h6MQ==', 'https://www.instagram.com/reel/C5y4eXzSAmE/'],
    image: 'bench-press-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/_gym%20_fitness%20_workout%20_excercise%20_instagood%20_instagram%20_viral%20_reels%20_instagym%20_motivation.mp4?updatedAt=1760781858219',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    bodyPart: 'Chest',
    sets: 3,
    reps: '12-15',
    instructions: [
        'Set the pulleys to chest height at a cable crossover station.',
        'Grab the handles with a neutral grip and step forward to create tension.',
        'Stand with your feet shoulder-width apart and a slight bend in your elbows.',
        'Bring the handles together in a wide arc in front of your chest.',
        'Squeeze your chest muscles at the peak of the movement.',
        'Slowly return to the starting position.',
    ],
    reelUrls: [],
    image: 'cable-fly-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/%E2%9D%8C%20Cable%20Chest%20Fly%20%E0%A4%95%E0%A4%B0%20%E0%A4%B0%E0%A4%B9%E0%A5%87%20%E0%A4%B9%E0%A5%8B%20%E0%A4%B2%E0%A5%87%E0%A4%95%E0%A4%BF%E0%A4%A8%20%E0%A4%B8%E0%A4%B9%E0%A5%80%20form%20%E0%A4%AA%E0%A4%A4%E0%A4%BE%20%E0%A4%B9%E0%A5%88%20%E0%A4%95%E0%A5%8D%E0%A4%AF%E0%A4%BE_%20%E0%A4%9C%E0%A5%8D%E0%A4%AF%E0%A4%BE%E0%A4%A6%E0%A4%BE%E0%A4%A4%E0%A4%B0%20%E0%A4%B2%E0%A5%8B%E0%A4%97%20%E0%A4%AF%E0%A5%87%20%E0%A4%97%E0%A4%B2%E0%A4%A4%E0%A5%80%20%E0%A4%95%E0%A4%B0%E0%A4%A4%E0%A5%87%20%E0%A4%B9%E0%A5%88%E0%A4%82%20%E0%A4%94%E0%A4%B0%20chest%20.mp4?updatedAt=1760789213191',
  },
  {
    id: 'dips',
    name: 'Dips',
    bodyPart: 'Chest',
    sets: 3,
    reps: '10-15',
    instructions: [
      'Grip parallel bars with your arms straight.',
      'Lower your body by bending your elbows until your shoulders are below your elbows.',
      'Push back up to the starting position.',
      'Lean forward to target your chest more.',
    ],
    reelUrls: [],
    image: 'dips-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/chest-dips.mp4',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    bodyPart: 'Back',
    sets: 3,
    reps: '10-12',
    instructions: [
      'Sit down on the lat pulldown machine and secure your knees under the pads.',
      'Grasp the bar with a wide grip, palms facing forward.',
      'Lean back slightly and pull the bar down to your upper chest, squeezing your back muscles.',
      'Slowly return the bar to the starting position with controlled movement.',
      'Repeat for the desired number of repetitions.',
    ],
    reelUrls: ['https://www.instagram.com/reel/C3t_oJ3SBrF/', 'https://www.instagram.com/reel/C6f5eP2S2b1/'],
    image: 'lat-pulldown-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/_gym%20_workout%20_excercise%20_.mp4?updatedAt=1760787280917',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    bodyPart: 'Back',
    sets: 4,
    reps: '5-8',
    instructions: [
        'Stand with your mid-foot under the barbell.',
        'Bend over and grab the bar with a shoulder-width grip.',
        'Bend your knees until your shins touch the bar.',
        'Lift your chest up and straighten your lower back.',
        'Take a big breath, hold it, and stand up with the weight.',
        'Return the weight to the floor by moving your hips back first, then bending your knees.'
    ],
    reelUrls: ['https://www.instagram.com/reel/C6a_oX9SeG_/', 'https://www.instagram.com/reel/C5p4f_mSg-d/'],
    image: 'deadlift-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/IS%20YOUR%20BACK%20NOT%20GROWING%20Master%20the%20deadlift%20with%20proper%20form%20to%20build%20strength,%20power,%20and%20musc.mp4?updatedAt=1760788216325',
  },
   {
    id: 'pull-up',
    name: 'Pull Up',
    bodyPart: 'Back',
    sets: 3,
    reps: 'As many as possible',
    instructions: [
      'Grasp the pull-up bar with an overhand grip, slightly wider than shoulder-width.',
      'Hang with your arms fully extended.',
      'Pull your body up until your chin is over the bar.',
      'Lower your body back down with control.',
      'Repeat.',
    ],
    reelUrls: [],
    image: 'pull-up-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/pull-ups.mp4',
  },
  {
    id: 'bent-over-row',
    name: 'Bent-Over Row',
    bodyPart: 'Back',
    sets: 4,
    reps: '8-10',
    instructions: [
      'Hold a barbell with a pronated grip (palms down).',
      'Bend your knees slightly and bend at the waist, keeping your back straight.',
      'Pull the bar towards your sternum, squeezing your back muscles.',
      'Lower the bar slowly and with control.',
    ],
    reelUrls: [],
    image: 'bent-over-row-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/bent-over-row.mp4',
  },
  {
    id: 'squat',
    name: 'Squat',
    bodyPart: 'Legs',
    sets: 4,
    reps: '10-12',
    instructions: [
        'Stand with your feet shoulder-width apart.',
        'Keep your chest up and core engaged.',
        'Lower your hips as if sitting in a chair.',
        'Go as low as you can while keeping your heels on the ground.',
        'Push through your heels to return to the starting position.',
    ],
    reelUrls: ['https://www.instagram.com/reel/C5_soA4S0yF/', 'https://www.instagram.com/reel/C6O-gD6S-yP/'],
    image: 'squat-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/Exersise%20for%20bigner_gym%20_fitness%20_workout%20_instagram%20_instagood%20_excercise%E2%80%8C%20_viral%20_reels%20_motiva.mp4?updatedAt=1760787404453',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    bodyPart: 'Legs',
    sets: 3,
    reps: '12-15',
    instructions: [
      'Sit on the leg extension machine with your back against the backrest.',
      'Place your shins under the padded bar.',
      'Extend your legs to lift the weight until they are straight.',
      'Hold the contraction for a moment.',
      'Slowly lower the weight back to the starting position.',
    ],
    reelUrls: [],
    image: 'leg-extension-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/%E2%9C%85%20Perfect%20Your%20Leg%20Extension%20Form%20_%20Stop%20Wasting%20Reps!%20__LegExtensionTips%20_LegExtensionForm%20_Le.mp4?updatedAt=1760790085321',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    bodyPart: 'Legs',
    sets: 4,
    reps: '10-15',
    instructions: [
      'Sit on the leg press machine with your feet on the platform.',
      'Push the platform away by extending your knees.',
      'Keep the movement slow and controlled.',
      'Do not lock your knees at the top of the movement.',
    ],
    reelUrls: [],
    image: 'leg-press-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/leg-press.mp4',
  },
  {
    id: 'lunges',
    name: 'Lunges',
    bodyPart: 'Legs',
    sets: 3,
    reps: '10-12 per leg',
    instructions: [
      'Step forward with one leg.',
      'Lower your hips until both knees are bent at a 90-degree angle.',
      'Keep your front knee directly above your ankle.',
      'Push off your front foot to return to the starting position.',
    ],
    reelUrls: [],
    image: 'lunges-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/lunges.mp4',
  },
  {
    id: 'bicep-curl',
    name: 'Bicep Curl',
    bodyPart: 'Arms',
    sets: 3,
    reps: '10-15',
    instructions: [
        'Stand or sit holding a dumbbell in each hand with an underhand grip.',
        'Keep your elbows close to your torso.',
        'Curl the weights toward your shoulders, squeezing your biceps.',
        'Slowly lower the weights back to the starting position.',
        'Repeat.',
    ],
    reelUrls: ['https://www.instagram.com/reel/C2s4Z_fLqG0/', 'https://www.instagram.com/reel/C6QW_R_rT_m/'],
    image: 'bicep-curl-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/Master%20bicep%20curls%20technique%20to%20unlock%20peak%20gainsFOLLOW%20FOR%20MKRE%20TUTORIALS!!!_workouts%20_workout%20.mp4?updatedAt=1760788578793',
  },
  {
    id: 'triceps-extensions',
    name: 'Triceps Extensions',
    bodyPart: 'Arms',
    sets: 3,
    reps: '10-15',
    instructions: [
      'Lie on a flat bench holding an EZ bar or two dumbbells above your chest.',
      'Keeping your upper arms stationary, lower the weight by bending your elbows.',
      'Continue until the weight is just above your forehead.',
      'Press the weight back up to the starting position, extending your arms.',
      'Repeat for the desired number of repetitions.',
    ],
    reelUrls: [],
    image: 'triceps-extensions-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/Stop%20doing%20Lying%20Triceps%20Extensions%20wrong%20%E2%9D%8CMost%20people%20make%20these%203%20mistakes-Elbows%20flaring%20out%20.mp4?updatedAt=1760789531711',
  },
  {
    id: 'hammer-curls',
    name: 'Hammer Curls',
    bodyPart: 'Arms',
    sets: 3,
    reps: '12-15',
    instructions: [
      'Stand with a dumbbell in each hand, palms facing your torso.',
      'Keeping your upper arms stationary, curl the weights forward.',
      'Squeeze your biceps and brachialis muscles.',
      'Slowly lower the dumbbells back to the start.',
    ],
    reelUrls: [],
    image: 'hammer-curls-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/hammer-curls.mp4',
  },
  {
    id: 'tricep-dips',
    name: 'Tricep Dips',
    bodyPart: 'Arms',
    sets: 3,
    reps: '12-15',
    instructions: [
      'Sit on the edge of a bench and place your hands on the edge, shoulder-width apart.',
      'Slide your butt off the bench with your legs extended out in front of you.',
      'Lower your body by bending your elbows until they are at a 90-degree angle.',
      'Push yourself back up to the starting position.',
    ],
    reelUrls: [],
    image: 'tricep-dips-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/tricep-dips.mp4',
  },
  {
    id: 'abdominal-training',
    name: 'Abdominal Training',
    bodyPart: 'Core',
    sets: 3,
    reps: '15-20',
    instructions: [
        'Lie on your back with your legs straight and together.',
        'Keep your arms straight above your head on the floor.',
        'In one movement, lift your legs and torso to a V-shape.',
        'Lower back down with control.',
        'Repeat for the desired number of repetitions.',
    ],
    reelUrls: [],
    image: 'abdominal-training-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/_sixpack%20_excercise%20_workout%20_gym%20_viral%20_instagram%20_fitness%20_instagood%20_viral%20_motivation%20_inst.mp4?updatedAt=1760787788895',
  },
  {
    id: 'plank',
    name: 'Plank',
    bodyPart: 'Core',
    sets: 3,
    reps: 'Hold for 30-60 seconds',
    instructions: [
      'Start in a push-up position, but with your weight on your forearms.',
      'Keep your body in a straight line from head to heels.',
      'Engage your core and glutes.',
      'Hold the position without letting your hips sag.',
    ],
    reelUrls: [],
    image: 'plank-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/plank.mp4',
  },
  {
    id: 'leg-raises',
    name: 'Leg Raises',
    bodyPart: 'Core',
    sets: 3,
    reps: '15-20',
    instructions: [
      'Lie on your back with your legs straight.',
      'Place your hands under your lower back for support.',
      'Raise your legs until they are perpendicular to the floor.',
      'Slowly lower your legs back down without touching the floor.',
    ],
    reelUrls: [],
    image: 'leg-raises-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/leg-raises.mp4',
  },
  {
    id: 'russian-twists',
    name: 'Russian Twists',
    bodyPart: 'Core',
    sets: 3,
    reps: '15-20 per side',
    instructions: [
      'Sit on the floor with your knees bent and feet off the ground.',
      'Lean back slightly to engage your core.',
      'Twist your torso from side to side, touching the floor on each side.',
      'Keep your back straight throughout.',
    ],
    reelUrls: [],
    image: 'russian-twists-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/russian-twists.mp4',
  },
  {
    id: 'shoulder-press',
    name: 'Shoulder Press',
    bodyPart: 'Shoulders',
    sets: 4,
    reps: '8-10',
    instructions: [
        'Stand with the barbell on your front shoulders, hands slightly wider than shoulder-width.',
        'Press the bar overhead until your arms are fully extended.',
        'Keep your core tight and avoid arching your back.',
        'Slowly lower the bar back to your shoulders.',
        'Repeat.',
    ],
    reelUrls: ['https://www.instagram.com/reel/C39eN0eLd9d/', 'https://www.instagram.com/reel/C4Xg3h_ruJd/'],
    image: 'shoulder-press-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/_Smith%20Shoulder%20Press-%20Are%20You%20Doing%20This%20Correctly__.mp4?updatedAt=1760788880414',
  },
  {
    id: 'traps',
    name: 'Traps',
    bodyPart: 'Shoulders',
    sets: 3,
    reps: '12-15',
    instructions: [
        'Stand holding dumbbells at your sides, palms facing your body.',
        'Lift your shoulders straight up towards your ears.',
        'Hold the peak contraction for a moment.',
        'Slowly lower the dumbbells back to the starting position.',
    ],
    reelUrls: [],
    image: 'traps-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/_Safe%20&%20Strong-%20How%20to%20Train%20Traps%20the%20Right%20Way__.mp4?updatedAt=1760789781900',
  },
  {
    id: 'lateral-raises',
    name: 'Lateral Raises',
    bodyPart: 'Shoulders',
    sets: 3,
    reps: '12-15',
    instructions: [
      'Stand with dumbbells in each hand at your sides.',
      'Raise your arms out to the sides until they are at shoulder level.',
      'Keep a slight bend in your elbows.',
      'Lower the weights back down slowly.',
    ],
    reelUrls: [],
    image: 'lateral-raises-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/lateral-raises.mp4',
  },
  {
    id: 'front-raises',
    name: 'Front Raises',
    bodyPart: 'Shoulders',
    sets: 3,
    reps: '12-15',
    instructions: [
      'Stand holding dumbbells in front of your thighs, palms facing down.',
      'Raise one arm straight out in front of you to shoulder height.',
      'Lower it back down and repeat with the other arm.',
      'Continue alternating arms.',
    ],
    reelUrls: [],
    image: 'front-raises-image',
    videoUrl: 'https://ik.imagekit.io/x6cjipsih/front-raises.mp4',
  },
];

export function getExercisesByBodyPart(bodyPart: BodyPart): Exercise[] {
  return exercises.filter((exercise) => exercise.bodyPart === bodyPart);
}

export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((exercise) => exercise.id === id);
}
